language: node_js
node_js:
  - "6"
  - "node"

install:
  - npm install
  - npm run flow && npm run build && npm run webpack && npm run webpack-prod

script: "npm run test"

notifications:
  email:
    recipients:
      - daily.bhou@gmail.com
    on_success: change
    on_failure: always
